spring:
  application:
    name: business-websocket
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.145:8848

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

server:
  port: 9004


management:
  endpoints:
    web:
      exposure:
        include: "*"
