spring:
  application:
    name: business-pims-web
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.145:8848

#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8080

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9001/oauth/token
      user-authorization-uri: http://localhost:9001/oauth/authorize
    resource:
      token-info-uri: http://localhost:9001/oauth/check_token
      user-info-uri: http://localhost:9001/oauth/user

dubbo:
  scan:
    base-packages: com.zzp.cloud.business.controller,com.zzp.cloud.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.247.145:8848

server:
  port: 9003
  servlet:
    context-path: /pims

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
